name: Build on Windows

on:
  push:
    branches:
      - go-rewrite

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      
      - name: Make build script executable
        working-directory: server
        run: chmod +x build.sh

      - name: Build Server
        working-directory: server
        run: sh build.sh

      - name: Build Server for Windows
        working-directory: server
        run: GOOS=windows GOARCH=amd64 go build -tags production -o build/server.exe main.go

      - name: Upload server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: |
            server/build/server.exe
            server/build/server.zip

  build-client:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      - name: Install pkg-config
        run: choco install pkgconfiglite -y
      - name: Make build script executable
        working-directory: client
        run: chmod +x build.sh

      - name: Build Client
        working-directory: client
        shell: bash
        run: |
          sh build.sh

      - name: Upload client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: |
            client/build/client.exe
            client/build/client.zip