name: Build on Windows

on:
  push:
    branches:
      - go-rewrite

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      
      - name: Make build script executable
        working-directory: server
        run: chmod +x build.sh

      - name: Build Server
        working-directory: server
        run: sh build.sh

      - name: Build Server for Windows
        working-directory: server
        run: GOOS=windows GOARCH=amd64 go build -tags production -o build/server.exe main.go

      - name: Upload server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: |
            server/build/server.exe
            server/build/server.zip

  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install Cross-compilation Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsndfile-dev mingw-w64 libwayland-dev
          git clone https://github.com/PortAudio/portaudio.git
          cd portaudio
          ./configure --host=x86_64-w64-mingw32 --enable-static --disable-shared
          make
          sudo make install

      - name: Set environment variables for PortAudio
        run: |
          export CGO_LDFLAGS="-L/usr/local/lib -lportaudio"
          export CGO_CFLAGS="-I/usr/local/include"
          
      - name: Set environment variables for cross-compilation toolchain
        run: |
          export CGO_ENABLED=1
          export GOOS=windows
          export GOARCH=amd64
          # Remove -mthreads if present
          export CGO_LDFLAGS=$(echo $CGO_LDFLAGS | sed 's/-mthreads//g')

      - name: Make build script executable
        working-directory: client
        run: chmod +x build.sh

      - name: Build Client with Static Linking
        working-directory: client
        run: sh build.sh

      - name: Upload client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: |
            client/build/client.zip
